CRATE TABLE COLLEGE
(
    ETSCODE CHAR(8) PRIMARY KEY,
    DATEESTABLISHED DATE CONSTRAINT ESTD_DATE NOT NULL,
    ISACCREDITED CHAR(1) CONSTRAINT ACC_STAT CHECK(ISCCREDITED IN ('Y', 'N'))
)

CREATE TABLE BUILDING
(
    NAME VARCHAR2(50) PRIMARY KEY,
    COLLEGE CHAR(8) REFERENCES COLLEGE(ETSCODE)
)

CREATE TABLE ROOM
(
    BUILDING VARCHAR2(50) CONSTRAINT B_NAME REFERENCES BUILDING(NAME),
    ROOM_NUM CHAR(4) CONSTRAINT ROOM_NUM CHECK(ROOM_NUM BETWEEN 0000 AND 9999) NOT NULL,
    SEATING_CAPACITY NUMBER(4),
    CONSTRAINT PRIM_KEY PRIMARY KEY (BUILDING, ROOM_NUM)
    
)

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_NUM CHAR(8) PRIMARY KEY,
    SSN CHAR(9) CONSTRAINT SSN UNIQUE,
    LAST_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    HIRED_DATE DATE,
    SALARY NUMBER(9,2) NOT NULL,
    COLLEGE CHAR(8) CONSTRAINT COLL_NAME REFERENCES COLLEGE(ETSCODE)
)